substitutions:
  _REGION: asia-northeast3
  _REPOSITORY: prooftutor
  _BACKEND_SERVICE: prooftutor-backend
  _VERIFIER_SERVICE: prooftutor-verifier

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/verifier:$SHORT_SHA
      - -f
      - training/verifier/Dockerfile
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/verifier:$SHORT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_VERIFIER_SERVICE}
      - --image
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/verifier:$SHORT_SHA
      - --region
      - ${_REGION}
      - --platform
      - managed

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/verifier:$SHORT_SHA

